// <auto-generated />
using System;
using ComplicadaMente.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComplicadaMente.Migrations
{
    [DbContext(typeof(ComplicadaMenteContext))]
    [Migration("20250727164102_AddQuantidadeToPeca")]
    partial class AddQuantidadeToPeca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ComplicadaMente.Models.Encomenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataEncomenda")
                        .HasColumnType("TEXT")
                        .HasColumnName("Data_Encomenda");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Preco_Total");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_Utilizador");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Encomenda");
                });

            modelBuilder.Entity("ComplicadaMente.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(9, 2)");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("ComplicadaMente.Models.ManualStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("QuebraCabecaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuebraCabecaId");

                    b.ToTable("ManualStep");
                });

            modelBuilder.Entity("ComplicadaMente.Models.Peca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Imagem")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuebraCabecaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_Quebra_Cabeca");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuebraCabecaId");

                    b.ToTable("Peca");
                });

            modelBuilder.Entity("ComplicadaMente.Models.PecaEncomenda", b =>
                {
                    b.Property<int>("EncomendaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_Encomenda");

                    b.Property<int>("PecaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_Peca");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("EncomendaId", "PecaId");

                    b.HasIndex("PecaId");

                    b.ToTable("Peca_Encomenda");
                });

            modelBuilder.Entity("ComplicadaMente.Models.QuebraCabeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Imagem")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quebra_Cabeca");
                });

            modelBuilder.Entity("ComplicadaMente.Models.QuebraCabecaEncomenda", b =>
                {
                    b.Property<int>("EncomendaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_Encomenda");

                    b.Property<int>("QuebraCabecaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_Quebra_Cabeca");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("EncomendaId", "QuebraCabecaId");

                    b.HasIndex("QuebraCabecaId");

                    b.ToTable("Quebra_Cabeca_Encomenda");
                });

            modelBuilder.Entity("ComplicadaMente.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utilizador");
                });

            modelBuilder.Entity("ComplicadaMente.Models.Encomenda", b =>
                {
                    b.HasOne("ComplicadaMente.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ComplicadaMente.Models.ManualStep", b =>
                {
                    b.HasOne("ComplicadaMente.Models.QuebraCabeca", "QuebraCabeca")
                        .WithMany()
                        .HasForeignKey("QuebraCabecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuebraCabeca");
                });

            modelBuilder.Entity("ComplicadaMente.Models.Peca", b =>
                {
                    b.HasOne("ComplicadaMente.Models.QuebraCabeca", "QuebraCabeca")
                        .WithMany()
                        .HasForeignKey("QuebraCabecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuebraCabeca");
                });

            modelBuilder.Entity("ComplicadaMente.Models.PecaEncomenda", b =>
                {
                    b.HasOne("ComplicadaMente.Models.Encomenda", "Encomenda")
                        .WithMany("PecaEncomendas")
                        .HasForeignKey("EncomendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComplicadaMente.Models.Peca", "Peca")
                        .WithMany("PecaEncomendas")
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encomenda");

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("ComplicadaMente.Models.QuebraCabecaEncomenda", b =>
                {
                    b.HasOne("ComplicadaMente.Models.Encomenda", "Encomenda")
                        .WithMany("QuebraCabecaEncomendas")
                        .HasForeignKey("EncomendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComplicadaMente.Models.QuebraCabeca", "QuebraCabeca")
                        .WithMany("QuebraCabecaEncomendas")
                        .HasForeignKey("QuebraCabecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encomenda");

                    b.Navigation("QuebraCabeca");
                });

            modelBuilder.Entity("ComplicadaMente.Models.Encomenda", b =>
                {
                    b.Navigation("PecaEncomendas");

                    b.Navigation("QuebraCabecaEncomendas");
                });

            modelBuilder.Entity("ComplicadaMente.Models.Peca", b =>
                {
                    b.Navigation("PecaEncomendas");
                });

            modelBuilder.Entity("ComplicadaMente.Models.QuebraCabeca", b =>
                {
                    b.Navigation("QuebraCabecaEncomendas");
                });
#pragma warning restore 612, 618
        }
    }
}
